apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoiceflow
  template:
    metadata:
      labels:
        app: invoiceflow
    spec:
      containers:
        - name: app
          image: 366451245116.dkr.ecr.us-west-1.amazonaws.com/invoiceflow-app:v1
          ports:
            - containerPort: 3000
