name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Assume AWS Role via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: Login to ECR
        run: |
          aws ecr get-login-password | \
          docker login --username AWS \
          --password-stdin 366451245116.dkr.ecr.us-west-1.amazonaws.com/invoiceflow-app


      - name: Build Docker Image
        run: |
          docker build -t 366451245116.dkr.ecr.us-west-1.amazonaws.com/invoiceflow-app
:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push 366451245116.dkr.ecr.us-west-1.amazonaws.com/invoiceflow-app
:${{ github.sha }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name invoiceflow-prod

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/invoiceflow \
          app=366451245116.dkr.ecr.us-west-1.amazonaws.com/invoiceflow-app
:${{ github.sha }}

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/invoiceflow
